### ISSUE TITLE
Package is not type: module

### ISSUE THREAD

**Issue by btaens** [tctien342/comfyui-sdk#6]
When I try to import ComfyAPI from the project like this:
```javascript
import {ComfyApi} from '@saintno/comfyui-sdk';
```
I get the following error:
> SyntaxError: Named export 'ComfyApi' not found. The requested module '@saintno/comfyui-sdk' is a CommonJS module, which may not support all module.exports as named exports.

It seems to think the package is commonjs, which is corroborated by the package.json of comfyui-sdk lacking `"type": "module"`.
If I edit your package and put that line in, everything works perfectly. I think it might just be missing it, currently I'm not sure how people are using it.

**Comment by tctien342** [comment]
Im using it with typescript project like NextJS and tRPC with bun, don't have that problem. Thank you for this info!

**Comment by tctien342** [comment]
@btaens I have update the package, you can reinstall it to see if your problem is solved.

**Comment by btaens** [comment]
Yeah, that did it. Works perfectly now. I was originally and now both testing it in a freshly initialized NPM project.
