### ISSUE TITLE
Multi value input nodes for Prompt Builder.

### ISSUE THREAD

**Issue by btaens** [tctien342/comfyui-sdk#7]
In ComfyUI, there's some nodes with a variable amount of inputs, such as Power Lora Loader from rgthree.
I'm not exactly sure what a good solution for this would look like, as unfortunately these don't even take a simple object as their nodes, but a pattern of node endpoints, in the case of Power Lora, every lora you add would look something like this: `26.inputs.lora_1`, `26.inputs.lora_2`, `26.inputs.lora_3` et cetera, each of which takes an object with multiple properties.
```json
      "lora_1": {
        "on": true,
        "lora": "somelora.safetensors",
        "strength": 0.8
      },
      "lora_2": {
        "on": true,
        "lora": "anotherlora.safetensors",
        "strength": 1
      },
      "lora_3": {
        "on": false,
        "lora": "athirdlora.safetensors",
        "strength": 0.6
      }
```
Again, not sure how to implement this with the current predefined PromptBuilder inputs if the amount of inputs we receive is also variable. Maybe some deeper level .input method that allows the setting of arbitrary values. I guess you could just set the .setInputNode for such fields at request time and create a new instance of PromptBuilder for each generation, but that would kind of make the point of PromptBuilder moot in this use case.

**Comment by tctien342** [comment]
@btaens How about i put a rawInput method that bypass typing ? So we can set any key we want into the workflow

**Comment by btaens** [comment]
Yeah, I think something like that is probably the best that can be done for this use case.

**Comment by tctien342** [comment]
I have add `setRawInputNode` `appendRawInputNode` and `setRawOutputNode`, this will allow string as mapping key; and every setInput and output will return clone of current PromptBuilder. Hope it can help

**Comment by btaens** [comment]
Hmm, while it allows setting of arbitrary node values, it still expects it to be one of the predefined parameters, so a variable amount of inputs is still an issue.

**Comment by tctien342** [comment]
> Hmm, while it allows setting of arbitrary node values, it still expects it to be one of the predefined parameters, so a variable amount of inputs is still an issue.

Lol, i forgot about it, let me quick fix!

**Comment by btaens** [comment]
Maybe a simple .rawInput function at prompting, so you can just set an arbitrary node to a value if you need it?

**Comment by tctien342** [comment]
> Maybe a simple .rawInput function at prompting, so you can just set an arbitrary node to a value if you need it?

I think, allow to create undefined path in `input` method is enough, when using with default `setInputNode`, typescript lint already tell the error if it not correct the path

**Comment by tctien342** [comment]
@btaens also i have put the `inputRaw` method so we can bind value directly into any key

**Comment by btaens** [comment]
The typing still expects an <input: I> value, so it still throws an error with the type must be one of the defined ones, though with inputRaw now that might be the point?
One other thing: .input and .inputRaw seem to return an object with the prototype of PromptBuilder,, which typescript doesn't support from what I can gather, causing not being able to chain inputs. I think it's because the typing is <typeof PromptBuilder> instead of just <PromptBuilder<I, O, T>, modifying index.d.ts seems to confirm this as it works perfectly afterwards.

**Comment by btaens** [comment]
Yeah, works perfectly! Thanks for the quick response!
